swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction API
      description: API for fetching a month transactions 
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: research transaction month
          required: true            
          schema:
            $ref: '#/definitions/TransactionMonth'
      produces:
        - application/json
      responses:
        '200':
          description: transaction of the month chooses retrieved successully
          schema:
            $ref: '#/definitions/ApiTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/retail:          
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction API
      description: API for fetching a transaction retails
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: research transaction retail
          required: true            
          schema:
            $ref: '#/definitions/TransactionRetail'
      produces:
        - application/json
      responses:
        '200':
          description: transaction retail retrieved successully
          schema:
            $ref: '#/definitions/ApiTransactionRetail'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transaction API
      description: API for updating a transaction retails
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction
          required: true        
          schema:
            $ref: '#/definitions/TransactionUpdating'
      produces:
        - application/json
      responses:
        '200':
          description: updating transaction retrieved successully
          schema:
            $ref: '#/definitions/ApiTransactionUpdating'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionMonth:
    properties:
      date:
        type: string
        description: date transaction
  TransactionRetail:
    properties:
      id:
        type: string
        description: id transaction
  TransactionUpdating:
    properties:
      transaction type:
        type: string
        description: transaction type
      category:
        type: string
        description: category choose user
      notes:
        type: string
        description: note user
  ApiTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          balance:
            type: number
  ApiTransactionRetail:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction type:
            type: string
          category:
           type: string
          notes:
            type: string
  ApiTransactionUpdating:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string        